### ISSUE TITLE
import api error

### ISSUE THREAD

**Issue by ghost** [jesuslosada/zabbix-client#2]
i will try use for configuration.import api, but this 'import' is python built-in library， cannot use it ? 
you can fix it, Thanks
![image](https://user-images.githubusercontent.com/20885056/48691857-0bb6e400-ec0f-11e8-9851-f68796940a07.png)

**Comment by jesuslosada** [comment]
Hi @mapengfei2016 . You can use `configuration.import_` instead. For reference: https://github.com/jesuslosada/zabbix-client/blob/542ef2785ddaec43c2a058b52d80e94b65cc3bc8/zabbix_client/api_wrapper.py#L204

**Comment by ghost** [comment]
Thanks for your response,I am trying to submit ， response this:
 File "/opt/prs_spider/deploy/zabbix_handler.py", line 273, in config_import
    return self.zb.configuration.import_(**kwargs)
  File "/opt/venv/lib/python2.7/site-packages/zabbix_client/api_wrapper.py", line 201, in call_wrapper
    return self.server_proxy.call(method, params=params)
  File "/opt/venv/lib/python2.7/site-packages/zabbix_client/api_wrapper.py", line 154, in call
    return self._call(method, params=params, auth=self._auth_token)
  File "/opt/venv/lib/python2.7/site-packages/zabbix_client/api_wrapper.py", line 161, in _call
    rpc_response = loads(content)
  File "/opt/venv/lib/python2.7/site-packages/zabbix_client/api_wrapper.py", line 105, in loads
    data=data)
zabbix_client.exceptions.JSONRPCError: Code: -32602, Message: Invalid params., Data: Cannot call method "configuration.import" without parameters.

I modify the api_wrapper.py print self.url and request: 
'http://10.0.81.21:9999/api_jsonrpc.php', '{"jsonrpc":"2.0","id":2,"auth":"f1144fce15c0a02684968af60cf5ab80","method":"configuration.import"}'

zabbix response: 
{u'jsonrpc': u'2.0', u'id': 2, u'error': {u'message': u'Invalid params.', u'code': -32602, u'data': u'Cannot call method "configuration.import" without parameters.'}}
May not be a problem with the tool， My zabbix version: 3.4 , install from sources

**Comment by jesuslosada** [comment]
You've solved the syntax issue and now you're able to contact the server, but the parameters are incorrect. `configuration.import` has 3 required parameters actually: https://www.zabbix.com/documentation/3.4/manual/api/reference/configuration/import
So the method call should look like this:
`zb.configuration.import(format='...', source='...', rules={...})`

**Comment by ghost** [comment]
Thanks, The problem has been solved, On export ,Need to exclude the template and host that comes with the system
